language: python
python:
  - "2.7"
# command to install dependencies
install:
 - sudo apt-get install subversion python python-dev libpq-dev libssl-dev libsasl2-dev libldap2-dev libxslt1.1 libxslt1-dev python-libxslt1 libexiv2-dev git
 - python bootstrap.py
 - bin/buildout install
# # command to run tests
script: "bin/django test"
