version: "2"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile-base
    image: mytardis-base
  builder:
    build:
      context: .
      dockerfile: Dockerfile-build
    volumes:
      - ./wheelhouse:/wheelhouse
      - ./tardis:/home/webapp/tardis
      - ./docs:/home/webapp/docs
    depends_on:
      - base
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ./wheelhouse:/wheelhouse
      - ./tardis:/home/webapp/tardis
      - ./docs:/home/webapp/docs
    depends_on:
      - builder
      - pg
      - mysql
    links:
      - pg
      - mysql
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
